services:
  mongo:
    image: mongo:6.0.14
    restart: always
    env_file: ./backend/.env.production
    volumes:
      - ./backend/docker-setup/mongo/prod-volume:/data/db
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: docker-setup/Dockerfile
    environment:
      - NODE_ENV=production
    env_file: ./backend/.env.production
    depends_on:
      - mongo
    volumes:
      - backend-logs:/app/logs
    networks:
      - default
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: docker-setup/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  backend-logs:

networks:
  default:
    name: backend-mern-docker-nginx
  frontend:
    name: frontend-mern-docker-nginx
