services:
  mongo:
    image: mongo:6.0.14
    ports:
      - "27017:27017"
    env_file: ./backend/.env.development
    volumes:
      - ./backend/docker-setup/mongo/dev-volume:/data/db
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: docker-setup/Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
      - ./backend/.env.development:/app/.env
    depends_on:
      - mongo
    networks:
      - default
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: docker-setup/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env.development:/app/.env.development
    depends_on:
      - backend
    networks:
      - frontend
      

networks:
  default:
    name: backend-mern-docker-nginx
  frontend:
    name: frontend-mern-docker-nginx
