version: '3.8'

services:
  mongo:
    image: mongo:6.0.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo-data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - mern

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - mern

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL:  http://localhost/api #Change for your domain in production
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - mern

volumes:
  mongo-data:

networks:
  mern:
